

# Validate yaml with: https://yamlchecker.com/

master:
       name: manager
       address: localhost
       file: main.rs

system:
      localization_only_mode: false
      vocabulary_file: "../Vocabulary/ORBvoc.txt"
      framesensor: Mono
      imusensor: None
      first_actor_name: TRACKING_FRONTEND # Name of actor to kick off pipeline

      # FPS
      fps: 10.0
      use_timestamps_file: false # Instead of running at a fixed fps, use timestamps from the dataset

      # RESULTS
      results_folder: "results"
      trajectory_file_name: "trajectory.txt"

      # DEBUGGING
      log_level: debug # options are [trace, debug, info, warn, error]
      check_deadlocks: true # Spawns a new thread to check for deadlocks every 2 secs, but slows stuff down.
      # To enable profiling, set features = ["enable"] for tracy-client in Cargo.toml
      # To turn on visualizer, uncomment visualizer actor below

modules:
      - 
        name: FEATURE_DETECTION
        tag: "feature detection"
        settings:
          - 
            name: max_features
            value: 2000
            type: i32
          - 
            name: scale_factor
            value: 1.2
            type: f64
          - 
            name: n_levels
            value: 8
            type: i32
          - 
            name: ini_th_fast
            value: 20
            type: i32
          - 
            name: min_th_fast
            value: 7
            type: i32

      -
        name: MATCHER
        tag: "matcher"
        settings:
          - 
            name: far_points_threshold
            value: 20.0
            type: f64
      -
        name: FEATURES
        tag: "features"
        settings:
          - 
            name: frame_grid_rows
            value: 48
            type: i32
          - 
            name: frame_grid_cols
            value: 64
            type: i32

            
actors:



      -
       name: TRACKING_FRONTEND
       tag: "orbslam tracking frontend"
       receiver_bound: 10
       settings:
          -

      -
       name: TRACKING_BACKEND
       tag: "orbslam tracking backend"
       receiver_bound: 10
       possible_paths:
                     -
                      from: tracking_frontend
                      to: localmapping
                      input: keypoints, descriptors
                      output: newkeyframe
       settings:
          - 
            name: recently_lost_cutoff
            value: 5
            type: i32
          - 
            name: frames_to_reset_IMU
            value: 30
            type: i32
          - 
            name: insert_KFs_when_lost
            value: true
            type: bool
          - 
            name: min_num_features
            value: 2000
            type: i32
          - 
            name: min_frames_to_insert_kf
            value: 0
            type: i32
          -
            name: max_frames_to_insert_kf
            value: 10
            type: i32

      -
       name: LOCAL_MAPPING
       tag: "orbslam local mapping"
       receiver_bound: 3
       settings:
          - 
            name: recently_lost_cutoff
            value: 5
            type: i32
          - 
            name: insert_KFs_when_lost
            value: true
            type: bool
          - 
            name: min_num_features
            value: 2000
            type: i32

      -
       name: LOOP_CLOSING
       tag: "orbslam2 loop closing"
       receiver_bound: -1
       settings:
          - 
            name: covisibility_consistency_threshold
            value: 3
            type: i32
